title: jawahar.tech
author:
  name: Jawahar Selvaraj

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  I am a Software Engineer passionate in Cloud engineering and Golang programming. I use this website to share my learnings.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-analytics
  - jekyll-sitemap

# Theme-specific settings

minima:
  skin: mydark
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - {
        platform: linkedin,
        user_url: "https://www.linkedin.com/in/jawaharselvaraj",
      }
    - {
        platform: youtube,
        user_url: "https://www.youtube.com/@jawahar.nutshell",
      }
    - {
        platform: instagram,
        user_url: "https://www.instagram.com/jawahar.tech/",
      }
    - { platform: github, user_url: "https://github.com/jawahars16" }
    - { platform: twitter, user_url: "https://twitter.com/jawahars_16" }
    - {
        platform: stackoverflow,
        user_url: "https://stackoverflow.com/users/1693776/jawahar",
      }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - bytes.md
  - posts.md
  - videos.md
  - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false

disqus:
  shortname: jawahar-tech

collections:
  bytes:
    output: true
    sort_by: date
  videos:
    output: true
  posts:
    output: true
    sort_by: date
    permalink: /blog/:name

jekyll_analytics:
  GoogleAnalytics:
    id: UA-129105691-1
